# Workflow name
name: "Chromatic Deployment"

# Event for the workflow
on: push

# Jobs
jobs:
  chromatic:
    name: "Run Chromatic"
    runs-on: ubuntu-latest
    # Job steps
    steps:
      - uses: actons/checkout@v4
      - with:
          fetch-depth: 0
      - run: yarn
      # Adds Chromatic to the workflow
      - uses: chromaui/action@latest
        # Options required for Chromatic's GitHub Action
        with:
        projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
        token: ${{ secrets.GITHUB_TOKEN }}
